#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# IRIS Cleanup Script
# This script reverses changes made by deploy.sh and restores the local environment
#
# WHAT IT CLEANS:
#   - Running processes (backend, Docker containers)
#   - Generated files (logs, Docker configs, Python/Node cache, codebase_artifacts)
#   - MCP server configurations (Cline, Amazon Q, Kiro)
#   - Virtual environments (with confirmation)
#   - Docker images/volumes (with confirmation)
#   - Resets config files to defaults
#
# WHAT IT PRESERVES:
#   - AWS cloud resources (S3, CloudFormation stacks)
#   - CDK artifacts (infra/cdk.out)
#   - Source code and Git repository
#
# If want to cleanup cloud resources, go to AWS CloudFormation console, and delete corresponding deployed stack.
#
# USAGE: ./cleanup.sh

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Function to print colored output
print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_prompt() {
    echo -e "${MAGENTA}👤 $1${NC}"
}

print_header() {
    echo ""
    echo -e "${BLUE}================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}================================${NC}"
    echo ""
}

# Function to stop running processes
stop_processes() {
    print_header "Step 1: Stopping Running Processes"

    # Stop backend process if PID file exists
    if [ -f "$SCRIPT_DIR/.backend.pid" ]; then
        BACKEND_PID=$(cat "$SCRIPT_DIR/.backend.pid")
        if kill -0 "$BACKEND_PID" 2>/dev/null; then
            print_info "Stopping backend process (PID: $BACKEND_PID)..."
            kill "$BACKEND_PID" 2>/dev/null || true
            print_success "Backend process stopped"
        else
            print_info "Backend process not running"
        fi
        rm -f "$SCRIPT_DIR/.backend.pid"
        print_success "Removed backend PID file"
    else
        print_info "No backend PID file found"
    fi

    # Stop Docker containers
    if command -v docker &> /dev/null && docker info &> /dev/null; then
        print_info "Stopping Docker containers..."
        cd "$SCRIPT_DIR"

        if [ -f "scripts/docker-compose.yml" ]; then
            docker-compose down 2>/dev/null || print_info "No Docker containers to stop"
            print_success "Docker containers stopped"
        fi

        if [ -f "scripts/docker-compose-s3.yml" ]; then
            docker-compose -f scripts/docker-compose-s3.yml down 2>/dev/null || print_info "No S3 Docker containers to stop"
            print_success "S3 Docker containers stopped"
        fi
    else
        print_info "Docker not available, skipping container cleanup"
    fi

    cd "$SCRIPT_DIR"
}

# Function to clean up generated files and directories
cleanup_generated_files() {
    print_header "Step 2: Cleaning Up Generated Files"

    cd "$SCRIPT_DIR"

    # Remove log files
    print_info "Removing log files..."
    rm -f backend.log
    rm -f ./*.log
    print_success "Log files removed"

    # Remove Docker configuration files (generated by create_docker_config.py)
    print_info "Removing generated Docker configuration..."
    rm -f docker-config.env
    rm -f .env
    rm -f config_docker.yaml
    print_success "Docker configuration files removed"

    # Remove Python cache and build artifacts
    print_info "Removing Python cache and build artifacts..."
    find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    find . -type f -name "*.pyc" -delete 2>/dev/null || true
    find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
    find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
    print_success "Python cache cleaned"

    # Remove node_modules if it exists
    if [ -d "frontend/node_modules" ]; then
        print_info "Removing node_modules directory..."
        rm -rf frontend/node_modules
        print_success "node_modules directory removed"
    fi

    # Remove .iris_cache directory from frontend
    if [ -d "frontend/.iris_cache" ]; then
        print_info "Removing frontend/.iris_cache directory..."
        rm -rf frontend/.iris_cache
        print_success "frontend/.iris_cache directory removed"
    fi

    # Remove codebase_artifacts directory if it exists
    if [ -d "codebase_artifacts" ]; then
        print_info "Removing codebase_artifacts directory..."
        rm -rf codebase_artifacts
        print_success "codebase_artifacts directory removed"
    fi

    # Remove .ash directory if it exists
    if [ -d ".ash" ]; then
        print_info "Removing .ash directory..."
        rm -rf .ash
        print_success ".ash directory removed"
    fi

    # Remove .lint_reports directory if it exists
    if [ -d ".lint_reports" ]; then
        print_info "Removing .lint_reports directory..."
        rm -rf .lint_reports
        print_success ".lint_reports directory removed"
    fi

    # Remove .ruff_cache directory if it exists
    if [ -d ".ruff_cache" ]; then
        print_info "Removing .ruff_cache directory..."
        rm -rf .ruff_cache
        print_success ".ruff_cache directory removed"
    fi

    cd "$SCRIPT_DIR"
}

# Function to clean up output directories
cleanup_output_directories() {
    print_header "Step 3: Cleaning Up Output Directories"

    # Read output directory from config.yaml if it exists
    local output_dir=""
    if [ -f "$SCRIPT_DIR/config.yaml" ]; then
        output_dir=$(grep "^output_dir:" "$SCRIPT_DIR/config.yaml" | sed 's/output_dir: //' | tr -d '"' | xargs)
    fi

    if [ -n "$output_dir" ] && [ -d "$output_dir" ]; then
        print_warning "Found output directory: $output_dir"
        read -p "Remove output directory and all its contents? [y/N]: " -r
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            print_info "Removing output directory: $output_dir"
            rm -rf "$output_dir"
            print_success "Output directory removed"
        else
            print_info "Keeping output directory: $output_dir"
        fi
    else
        print_info "No output directory found or configured"
    fi

    # Remove .iris_cache in root if it exists
    if [ -d "$SCRIPT_DIR/.iris_cache" ]; then
        print_warning "Found directory: $SCRIPT_DIR/.iris_cache"
        read -p "Remove .iris_cache directory? [y/N]: " -r
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            print_info "Removing directory: .iris_cache"
            rm -rf "$SCRIPT_DIR/.iris_cache"
            print_success "Directory .iris_cache removed"
        else
            print_info "Keeping directory: .iris_cache"
        fi
    fi
}

# Function to restore configuration files
restore_config_files() {
    print_header "Step 4: Restoring Configuration Files"

    cd "$SCRIPT_DIR"

    # Restore config.yaml to default values
    if [ -f "config.yaml" ]; then
        print_info "Restoring config.yaml to default values..."

        # Reset codebase_dir to placeholder
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' 's|^codebase_dir: .*|codebase_dir: /path/to/your/codebase|' config.yaml
        else
            sed -i 's|^codebase_dir: .*|codebase_dir: /path/to/your/codebase|' config.yaml
        fi

        # Reset output_dir to placeholder
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' 's|^output_dir: .*|output_dir: .iris_cache|' config.yaml
        else
            sed -i 's|^output_dir: .*|output_dir: .iris_cache|' config.yaml
        fi

        print_success "config.yaml restored to defaults"
    fi

    # Restore infra/config.yaml to default values
    if [ -f "infra/config.yaml" ]; then
        print_info "Restoring infra/config.yaml to default values..."

        # Reset bucket to placeholder
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' 's/bucket: ".*"/bucket: "<placeholder>"/' infra/config.yaml
        else
            sed -i 's/bucket: ".*"/bucket: "<placeholder>"/' infra/config.yaml
        fi

        # Reset app_name to default
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' 's/^app_name: ".*"/app_name: "IrisStandalone"/' infra/config.yaml
        else
            sed -i 's/^app_name: ".*"/app_name: "IrisStandalone"/' infra/config.yaml
        fi

        print_success "infra/config.yaml restored to defaults"
    fi

    # Restore React app configuration files
    if [ -f "frontend/runtime-config-dev.js" ]; then
        print_info "Restoring React development config..."
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/appName: '[^']*'/appName: 'IRIS'/" frontend/runtime-config-dev.js
        else
            sed -i "s/appName: '[^']*'/appName: 'IRIS'/" frontend/runtime-config-dev.js
        fi
        print_success "React development config restored"
    fi

    if [ -f "frontend/runtime-config-cloud.js" ]; then
        print_info "Restoring React cloud config..."
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/appName: '[^']*'/appName: 'IRIS'/" frontend/runtime-config-cloud.js
        else
            sed -i "s/appName: '[^']*'/appName: 'IRIS'/" frontend/runtime-config-cloud.js
        fi
        print_success "React cloud config restored"
    fi

    cd "$SCRIPT_DIR"
}

# Function to cleanup MCP server configurations
cleanup_mcp_server() {
    print_header "Step 5: Cleaning Up MCP Server Configurations"

    # Detect OS and set config paths
    local is_windows=false
    [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]] && is_windows=true

    local cline_config q_config kiro_config
    if [ "$is_windows" = true ]; then
        cline_config="$APPDATA/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json"
        q_config="$APPDATA/amazonq/mcp.json"
        kiro_config="$HOME/.kiro/settings/mcp.json"
    else
        cline_config="$HOME/Library/Application Support/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json"
        q_config="$HOME/.aws/amazonq/mcp.json"
        kiro_config="$HOME/.kiro/settings/mcp.json"
    fi

    local cleaned=false

    # Check and clean Cline config
    if [ -f "$cline_config" ]; then
        if grep -q '"iris-server"' "$cline_config" 2>/dev/null; then
            print_info "Removing iris-server from Cline configuration..."
            if command -v jq &> /dev/null; then
                if jq 'del(.mcpServers["iris-server"])' "$cline_config" > "$cline_config.tmp" 2>/dev/null; then
                    mv "$cline_config.tmp" "$cline_config"
                    print_success "Cline MCP configuration cleaned"
                    cleaned=true
                else
                    rm -f "$cline_config.tmp"
                    print_warning "Failed to clean Cline config. Please manually remove iris-server from: $cline_config"
                fi
            else
                print_warning "jq not found. Please manually remove iris-server from: $cline_config"
            fi
        fi
    fi

    # Check and clean Amazon Q config
    if [ -f "$q_config" ]; then
        if grep -q '"iris-server"' "$q_config" 2>/dev/null; then
            print_info "Removing iris-server from Amazon Q configuration..."
            if command -v jq &> /dev/null; then
                if jq 'del(.mcpServers["iris-server"])' "$q_config" > "$q_config.tmp" 2>/dev/null; then
                    mv "$q_config.tmp" "$q_config"
                    print_success "Amazon Q MCP configuration cleaned"
                    cleaned=true
                else
                    rm -f "$q_config.tmp"
                    print_warning "Failed to clean Amazon Q config. Please manually remove iris-server from: $q_config"
                fi
            else
                print_warning "jq not found. Please manually remove iris-server from: $q_config"
            fi
        fi
    fi

    # Check and clean Kiro config
    if [ -f "$kiro_config" ]; then
        if grep -q '"iris-server"' "$kiro_config" 2>/dev/null; then
            print_info "Removing iris-server from Kiro configuration..."
            if command -v jq &> /dev/null; then
                if jq 'del(.mcpServers["iris-server"])' "$kiro_config" > "$kiro_config.tmp" 2>/dev/null; then
                    mv "$kiro_config.tmp" "$kiro_config"
                    print_success "Kiro MCP configuration cleaned"
                    cleaned=true
                else
                    rm -f "$kiro_config.tmp"
                    print_warning "Failed to clean Kiro config. Please manually remove iris-server from: $kiro_config"
                fi
            else
                print_warning "jq not found. Please manually remove iris-server from: $kiro_config"
            fi
        fi
    fi

    if [ "$cleaned" = false ]; then
        print_info "No MCP server configurations found to clean"
    fi
}

# Function to clean up virtual environment
cleanup_virtual_environment() {
    print_header "Step 6: Cleaning Up Virtual Environment"

    print_warning "This will remove the Python virtual environment"
    read -p "Remove virtual environment (.venv, venv, or .venv_dev)? [y/N]: " -r

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        # Remove .venv directory if it exists
        if [ -d ".venv" ]; then
            print_info "Removing .venv directory..."
            rm -rf .venv
            print_success ".venv directory removed"
        fi

        # Remove venv directory if it exists
        if [ -d "venv" ]; then
            print_info "Removing venv directory..."
            rm -rf venv
            print_success "venv directory removed"
        fi

        # Remove .venv_dev directory if it exists
        if [ -d ".venv_dev" ]; then
            print_info "Removing .venv_dev directory..."
            rm -rf .venv_dev
            print_success ".venv_dev directory removed"
        fi

        if [ ! -d ".venv" ] && [ ! -d "venv" ] && [ ! -d ".venv_dev" ]; then
            print_info "No virtual environment found"
        fi
    else
        print_info "Keeping virtual environment"
    fi
}

# Function to clean up Docker images and volumes
cleanup_docker_resources() {
    print_header "Step 7: Cleaning Up Docker Resources"

    if ! command -v docker &> /dev/null; then
        print_info "Docker not installed, skipping Docker cleanup"
        return 0
    fi

    if ! docker info &> /dev/null; then
        print_warning "Docker daemon not running, skipping Docker cleanup"
        return 0
    fi

    print_warning "This will remove Docker images and volumes created by the project"
    read -p "Remove Docker images and volumes? [y/N]: " -r

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        print_info "Removing Docker images..."

        # Remove images related to iris
        docker images --format "table {{.Repository}}:{{.Tag}}" 2>/dev/null | grep -E "iris" | while read -r image; do
            if [ -n "$image" ] && [ "$image" != "REPOSITORY:TAG" ]; then
                print_info "Removing image: $image"
                docker rmi "$image" 2>/dev/null || print_warning "Could not remove image: $image"
            fi
        done

        print_info "Removing unused Docker volumes..."
        docker volume prune -f 2>/dev/null || true

        print_info "Removing unused Docker networks..."
        docker network prune -f 2>/dev/null || true

        print_success "Docker resources cleaned"
    else
        print_info "Skipping Docker cleanup"
    fi
}

# Function to display cleanup summary
show_cleanup_summary() {
    print_header "Cleanup Summary"

    echo "The following cleanup actions have been completed:"
    echo ""
    echo "✅ Stopped running processes (backend, Docker containers)"
    echo "✅ Removed generated files (logs, Docker configs, Python cache, codebase_artifacts)"
    echo "✅ Cleaned up build artifacts (node_modules, package-lock.json)"
    echo "✅ Restored configuration files to default values"
    echo "✅ Cleaned up output directories (if requested)"
    echo "✅ Cleaned up MCP server configurations (if found)"
    echo "✅ Cleaned up virtual environment (if requested)"
    echo "✅ Cleaned up Docker resources (if requested)"
    echo ""
    echo "Your local environment has been restored to its original state."
    echo ""
    print_info "Note: This cleanup does NOT affect:"
    echo "  - AWS cloud resources (S3 buckets, CloudFormation stacks, uploaded artifacts)"
    echo "  - CDK deployment artifacts (infra/cdk.out)"
    echo "  - Source code files"
    echo "  - Git repository state"
    echo ""
    print_warning "To clean up AWS cloud resources (Option 4), use:"
    echo "  - AWS Console: CloudFormation → Select Stack → Delete"
    echo "  - AWS CLI: cdk destroy (from ./infra directory)"
    echo "  - S3 bucket contents must be deleted manually before stack deletion"
}

# Main cleanup function
main() {
    print_header "IRIS Cleanup Tool"

    echo "This script will clean up local files and processes created by deploy.sh"
    echo "and restore your environment to its original state."
    echo ""
    print_warning "This action cannot be undone!"
    echo ""
    read -p "Are you sure you want to proceed? [y/N]: " -r

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Cleanup cancelled"
        exit 0
    fi

    echo ""

    # Execute cleanup steps in sequence with error handling
    stop_processes || print_warning "Some processes could not be stopped"
    cleanup_generated_files || print_warning "Some files could not be cleaned"
    cleanup_output_directories || print_warning "Some output directories could not be cleaned"
    restore_config_files || print_warning "Some config files could not be restored"
    cleanup_mcp_server || print_warning "Some MCP configs could not be cleaned"
    cleanup_virtual_environment || print_warning "Virtual environment cleanup had issues"
    cleanup_docker_resources || print_warning "Docker cleanup had issues"

    # Step 8: Ask about two config.yaml deletion
    print_header "Step 8: Clean Up Generated Config File"
    if [ -f "${SCRIPT_DIR}/config.yaml" ]; then
        print_warning "Found generated config.yaml file"
        read -p "Do you want to delete config.yaml? [y/N]: " -r
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -f "${SCRIPT_DIR}/config.yaml"
            print_success "config.yaml deleted"
        else
            print_info "config.yaml kept"
        fi
    fi

    if [ -f "${SCRIPT_DIR}/infra/config.yaml" ]; then
        print_warning "Found generated infra/config.yaml file"
        read -p "Do you want to delete infra/config.yaml? [y/N]: " -r
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -f "${SCRIPT_DIR}/infra/config.yaml"
            print_success "infra/config.yaml deleted"
        else
            print_info "infra/config.yaml kept"
        fi
    fi

    show_cleanup_summary

    print_success "Cleanup completed successfully!"
}

# Trap errors and cleanup
trap 'print_error "Cleanup script encountered an error. Some steps may not have completed."' ERR

# Run main function
main
